spring:
  #mybatis-plus的配置
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://rm-2vc34b66ob8em02bpio.mysql.cn-chengdu.rds.aliyuncs.com:3306/intellia2?serverTimezone=Asia/Shanghai
  #    username: dlf
  #    password: 2441086385Dlf
  #设置cache存到redis里面
  #  cache:
  #    type: redis
  #redis的配置
  #  redis:
  #    database: 1
  #    host: 150.158.174.169
  ##    host: 127.0.0.1
  #    port: 6379
  #    password: dailinfeng_pass
  servlet:
    #上传文件大小限制  开大一点
    multipart:
      max-file-size: 99999999MB
      max-request-size: 99999999MB

#mybatis-plus:
#  configuration:
#    #    驼峰命名打开
#    map-underscore-to-camel-case: true
#配置 打印SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
data:
  save: /Users/dailinfeng/Desktop/dataops/result
  dataPath: /Users/dailinfeng/Desktop/dataops/data
  serverBaseUrl: http://127.0.0.1:8000/task
server:
  port: 9999
#调用Python端服务配置
forest:
  max-connections: 1000 # 连接池最大连接数，默认值为500
  max-route-connections: 500 # 每个路由的最大连接数，默认值为500
  timeout: 900000 # 请求超时时间，单位为毫秒, 默认值为3000
  connect-timeout: 3000 # 连接超时时间，单位为毫秒, 默认值为2000
  retry-count: 1 # 请求失败后重试次数，默认为0次不重试
  logEnabled: true # 打开或关闭日志，默认为true
  log-request: true # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true # 打开/关闭Forest响应内容日志（默认为 false）
  variables:
    baseUrl: http://127.0.0.1:8000
    notifyUrl: http://10.131.18.162:5700   #qq 机器人的url
##签发token token认证的
#jwtp:
#  store-type: 0  #0-redisTokenStore 1-jdbcTokenStore 2-jwtTokenStore 默认是0
##  secret-key: 123456 #123456#生成token的密钥 redis和jdbc类型可以不指定 jwt模式下必须指定
#  path: /**  #拦截路径，默认是/**
#  exclude-path: /swagger-resources/**,/v3/** ,swagger-ui.html#/,/error,/image/upload #排除拦截路径，默认无
#  url-perm-type: 2  #url自动对应权限方式，0 简易模式，1 RESTful模式，2 接口处根据注解校验

